---
title: "Bivariate_analysis on different datasets"
author: "Shyamolina Ghosh"
date: "February 8, 2018"
output: 
  html_document:
    fig_caption: yes
    fig_width: 5
    highlight: zenburn
    keep_tex: yes
    number_sections: yes
    df_print: kable # data frame printing option
fontsize: 11pt
---
updated on `r Sys.Date()`
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<mark>*Code preloaded*</mark>

```{r BIVAN, echo=F}
#----------------------
rm(list=ls())
graphics.off()
library(copula)
library(VineCopula)
#----------------------
source("OurBiCopSelect.R")
#----------------------
# This function takes a bivariable dataset (matrix or dataframe)
# Output : a plot(optional) and rankings as a dataframe

getcopula<-function(d,ploton){
 
  #get ranks
  v1<-d[,1]
  v2<-d[,2]
  
  #get ranks modified now
  if(max(rbind(v1,v2))>=1){
    v1<-pobs(v1)
    v2<-pobs(v2)
  }
  
  if(ploton==T){
    plot(v1,v2,type="p",col="red",xlab=expression(v[1]),ylab=expression(v[2]),cex.lab=1)
  }

  cop<-data.frame(v1=v1,v2=v2)
  return(cop)
}

#Test the function
#cop<-claytonCopula(8,2)
#d<-rCopula(1000,cop)
#cop_rank<-(getcopula(d=d,ploton=T))

#--------------------------------------------------------------------------------------------------
# This function fits the data within the given set of families
# Input : given data, a vector of possible copula families, indep_test_p threshold
# output : a list of two dataframe: 1. all possible info for bestfit cop, 
#                          2. info for all possible fit cop(copcode,copname,par,par1,logLik,AIC,BIC)

fit_BIV<-function(d,families,level=0.05){
  
  num_indep<-0
  
  m<-getcopula(d,ploton=F)
  u1<-m[,1]
  u2<-m[,2]
       
  ans<-OurBiCopSelect(u1,u2,families,AICBIC="AIC",level=0.05,numBS=100,gofnormal=T)
  if(ans$IndepTestRes<level){
    gfc_numBS<-100
    gfc_p_CvM<-ans$GofRes_CvM
    gfc_p_KS<-ans$GofRes_KS
    gfc_p_CvM_stat<-ans$GofRes_CvM_stat
    gfc_p_KS_stat<-ans$GofRes_KS_stat
    
    gfc_normal_p_CvM<-ans$GofRes_Normal_CvM
    gfc_normal_p_KS<-ans$GofRes_Normal_KS
    gfc_normal_p_CvM_stat<-ans$GofRes_Normal_CvM_stat
    gfc_normal_p_KS_stat<-ans$GofRes_Normal_KS_stat
    
    pmin<-min(ans$GofRes_CvM,ans$GofRes_KS,ans$GofRes_Normal_CvM,ans$GofRes_Normal_KS)
    if(pmin<0.2){
      ans2<-OurBiCopSelect(u1,u2,families,AICBIC="AIC",level=0.05,numBS=1000,gofnormal=T)
      gfc_numBS<-1000
      gfc_p_CvM<-ans2$GofRes_CvM
      gfc_p_KS<-ans2$GofRes_KS
      gfc_p_CvM_stat<-ans$GofRes_CvM_stat
      gfc_p_KS_stat<-ans$GofRes_KS_stat
      
      gfc_normal_p_CvM<-ans2$GofRes_Normal_CvM
      gfc_normal_p_KS<-ans2$GofRes_Normal_KS
      gfc_normal_p_CvM_stat<-ans$GofRes_Normal_CvM_stat
      gfc_normal_p_KS_stat<-ans$GofRes_Normal_KS_stat
    }
    
    info<-ans$InfCritRes
    info_ord<-info[order(info[,6],decreasing = F),] # ordered according to min to max AIC
    
    
  }else{
    num_indep<-num_indep+1
    gfc_numBS<-Inf
    gfc_p_CvM<-Inf
    gfc_p_KS<-Inf
    gfc_p_CvM_stat<-Inf
    gfc_p_KS_stat<-Inf
    gfc_normal_p_CvM<-Inf 
    gfc_normal_p_KS<-Inf
    gfc_normal_p_CvM_stat<-Inf
    gfc_normal_p_KS_stat<-Inf
    info_ord<-data.frame(copname="Indep")
  }
          
#-----------------------------------------------------------------------------
# Save the results
  RES<-list(data.frame(num_indep_location=num_indep,
               gfc_numBS=gfc_numBS,
               gfc_p_CvM=gfc_p_CvM,
               gfc_p_KS=gfc_p_KS,
               gfc_p_CvM_stat=gfc_p_CvM_stat,
               gfc_p_KS_stat=gfc_p_KS_stat,
               gfc_normal_p_CvM=gfc_normal_p_CvM,
               gfc_normal_p_KS=gfc_normal_p_KS,
               gfc_normal_p_CvM_stat=gfc_normal_p_CvM_stat,
               gfc_normal_p_KS_stat=gfc_normal_p_KS_stat),
               info_ord=info_ord)
  
  return(RES)
  
}

#-------------------------------------------------------------------------------------
#Check the function
#families<-c(1,3,5)
#x<-fit_BIV(d,families)
#---------------------------------------------------------------------------------------------------------

```

# Testing code

* **About the dataset :** This data came from a clayton with param=8

```{r loaddatatest, echo=F}
# here you can directly load the bivariate data to the variable d
# or you can save the bivariate data to d after some data extraction
d<-readRDS("Data/givendata.RDS")
```

* **Copula plot of the data :**
```{r callingcodetest, echo=F, cache=T, cache.extra=list(d)}
#Test the function
cop_rank<-(getcopula(d=d,ploton=T))

families<-c(1,3,5)
x<-fit_BIV(d=d,families)
```

* **Results :**
```{r restest, echo=F}
knitr::kable(x[[1]])
knitr::kable(x[[2]])
```


# Results from dataset1 : Prof. T. Loecke
<mark>*You have to edit this section*</mark>

* **About the dataset :** <mark>*Please provide a brief description*</mark>

```{r loaddata1, echo=F}
# here you can directly load the bivariate data to the variable d
# or you can save the bivariate data to d after some data extraction
d<-readRDS("Data/givendata.RDS")
```

* **Copula plot of the data :**
```{r callingcode1, echo=F, cache=T, cache.extra=list(d)}
#Test the function
cop_rank<-(getcopula(d=d,ploton=T))

families<-c(1,3,5)
x<-fit_BIV(d=d,families)
```

* **Results :**
```{r res1, echo=F}
knitr::kable(x[[1]])
knitr::kable(x[[2]])
```


# Results from dataset2 : Prof. ____________