---
title: "BIVAN makefile, compiliation notes"
author: "Daniel Reuman"
date: ""
output: pdf_document
---

<!--checkpoint package-->
```{r checkpoint_chunk, echo=F, warning=F, message=F, results="hide"}
library(checkpoint)
library(captioner)
library(rmarkdown)
if (!dir.exists("./.checkpoint/")){
  dir.create("./.checkpoint/")
}
checkpoint("2018-03-29",checkpointLocation = "./")
```

# Get tex files and pdf files for the supp mat, but the pdf files 
#are missing the external references 

```{r tex_for_supp_mat}
rmarkdown::render(input="SupportingInformation.Rmd") 
```

# Get tex files and pdf files for the main text, but the pdf files 
#are missing the external references 

```{r tex_for_main_text}
rmarkdown::render(input="Paper.Rmd") 
```

# Now recompile the latex

```{r recompile_latex}
#do it once
system2(command="pdflatex",args="SupportingInformation.tex",stdout=TRUE,stderr=TRUE)
system2(command="pdflatex",args="Paper.tex",stdout=TRUE,stderr=TRUE)

#do it again to make sure to get the external references right
system2(command="pdflatex",args="SupportingInformation.tex",stdout=TRUE,stderr=TRUE)
system2(command="pdflatex",args="Paper.tex",stdout=TRUE,stderr=TRUE)
```