---
title: "Unit tests"
author: "Shyamolina Ghosh and Daniel Reuman"
date: "March 7, 2018"
output: pdf_document
---

<!--Basic setup-->
```{r setup, echo=F}
#Basic setup

#A function needed for caching
source("mtime.R")
```

# Test flexible copula functions

Set up some test data:
```{r test_copula_function_flexible_data, echo=T}
dl<-seq(from=0.1,by=0.1,to=0.9)
ep<-c(.05,-.03,.02,-.1,-.09,.05,.1,-.08,.05)
vi<-dl+ep
vj<-dl-ep
```

A plot function to use in testing:
```{r plot_vivj,echo=T}
plot_vivj<-function(vi,vj,lb,ub){
plot(vi,vj,col="red",xlim=c(0,1),ylim=c(0,1),asp=1,cex.axis=0.5)
axis(1, at = seq(0, 1, by = 0.1),cex.axis=0.5)
abline(a=2*lb,b=-1,col="blue")
abline(a=2*ub,b=-1,col="green4")
abline(a=0,b=1)
rect(0,0,1,1)
}
```

Test the cor statistic:
```{r test_copula_function_flexible_cor, echo=T}
source("CopulaFunctions_flexible.R")
lb=.05
ub=.45
plot_vivj(vi,vj,lb,ub)
h<-Corbds(vi,vj,lb=lb,ub=ub)
inds<-1:4
ht<-sum((vi[inds]-mean(vi))*(vj[inds]-mean(vj)))/((length(vi)-1)*sqrt(var(vi)*var(vj)))

if (abs(h-ht)<1e-12)
{
  print("passed")
}
```

Test the D2 statistic:
```{r test_copula_function_flexible_D2, echo=T}
source("CopulaFunctions_flexible.R")
lb=.05
ub=.45
h<-D2bds(vi,vj,lb=lb,ub=ub)
if (abs((sum(ep[1:4]^2)/2)-h)<1e-12)
{
  print("passed")
}
```

Test the P statistic:
```{r test_copula_function_flexible_P, echo=T}
source("CopulaFunctions_flexible.R")

vi<-c(vi[3],vi[7],vi[9])
vj<-c(vj[3],vj[7],vj[9])

#Test for when two parallel boundary lines are on the left side of vi+vj=1 line
lb=0
ub=.45
plot_vivj(vi=vi,vj=vj,lb=lb,ub=ub)
hl<-Pbds(vi,vj,lb=lb,ub=ub)

#plot the step fn
plot(hl$dist_S,hl$S,type="b")

#calculate the area under the curve 
vertices<-unique(hl$dist_S[(hl$dist_S!=0)])
area_S<-(vertices[2]-vertices[1])*1
area_S

area_S==hl$Au_S # it's a check

hl$Au_Si

#P stat value for lower tail
(area_S-hl$Au_Si)==hl$abs_res

#Test for when two parallel boundary lines are on the right side of vi+vj=1 line
lb=0
ub=.4 # if ub=0.45 then hu$Au_Si = hl$Au_Si : so, it's a check on Au_Si
plot_vivj(vi=vi,vj=vj,lb=(1-ub),ub=(1-lb))

#calling P stat for upper tail
hu<-Pbds(vi,vj,lb=(1-ub),ub=(1-lb))

#plot the step fn
plot(hu$dist_S,hu$S,type="b")

#calculate the area under the curve 
w1<-unique(hu$dist_S[(hu$dist_S!=0)])
w1  #x-coord where the jump occurs
h1<-unique(hu$S)
h1  #y-coord where the jump occurs
area_S<-((w1[2]-w1[1])*(h1[2]-h1[1]))+((w1[3]-w1[2])*(h1[3]-h1[1]))
area_S

area_S==hu$Au_S  # it's a check

hu$Au_Si

#P stat value for upper tail
(area_S-hu$Au_Si)==hu$abs_res 

#Test for when two parallel boundary lines are on opposite sides of vi+vj=1 line
lb=0.3
ub=0.8

#calling P stat for middle section
hm<-Pbds(vi,vj,lb=lb,ub=ub)

#(vi,vj) plot in unit box : middle section
plot_vivj(vi=vi,vj=vj,lb=lb,ub=ub)

#plot the step fn
plot(hm$dist_S,hm$S,type="b")

#calculate the area under the curve 
w1<-unique(hm$dist_S[(hm$dist_S!=0)])
w1  #x-coord where the jump occurs
h1<-unique(hm$S)
h1  #y-coord where the jump occurs
area_S<-((w1[2]-w1[1])*(h1[2]-h1[1]))+((w1[3]-w1[2])*(h1[3]-h1[1]))
area_S

area_S==hm$Au_S # it's a check

hm$Au_Si

#P stat value for middle section
(area_S-hm$Au_Si)==hm$abs_res
```

# Test skewness and third central moment functions

```{r}
source("SkewnessAnd3CentMom.R")
#Dan fill in - see if there is testing text in the file itself 
```

# Test surrogate functions

Test the copsurrog2d function:
```{r test_copsurrog2d, echo=T}
library("VineCopula")
source("copsurrog2d.R")
set.seed(101)

#***basic tests of the function using kendall-preserving surrogates
datcop<-claytonCopula(5,2)
numpts<-1000
m<-rCopula(numpts,datcop)
plot(m[,1],m[,2],type='p')
rect(0,0,1,1)

tarcop<-gumbelCopula(3,2)

res<-copsurrog2d(m,tarcop,'kendall',3)
dim(res) 
if (sum(dim(res)[1:2]==dim(m))==2)
{
  print("passed")
} else
{
  print("dim of output is wrong")
}

cor(m[,1],m[,2],method='kendall') #this should be similar to the following 
cor(res[,1,1],res[,2,1],method='kendall')
cor(res[,1,2],res[,2,2],method='kendall')
cor(res[,1,3],res[,2,3],method='kendall')

plot(res[,1,1],res[,2,1],type='p') #should look like a Gumbel
rect(0,0,1,1)
BiCopGofTest(res[,1,1],res[,2,1],family=4) #should indicate an acceptable fit
BiCopGofTest(res[,1,2],res[,2,2],family=4) #should indicate an acceptable fit
BiCopGofTest(res[,1,3],res[,2,3],family=4) #should indicate an acceptable fit

if (sum(sort(res[,1,1])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,1])==sort(m[,2]))==numpts &&
    sum(sort(res[,1,2])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,2])==sort(m[,2]))==numpts &&
    sum(sort(res[,1,3])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,3])==sort(m[,2]))==numpts)
{
  print("passed")
} else
{
  print("Columns of output of copsurrog should be permutations of the corresponding columns of the input")
}

#basic tests using spearman preserving surrogates
res<-copsurrog2d(m,tarcop,'spearman',3)
dim(res)
if (sum(dim(res)[1:2]==dim(m))==2)
{
  print("passed")
} else
{
  print("dim of output is wrong")
}

cor(m[,1],m[,2],method='spearman') #this should be similar to the following 
cor(res[,1,1],res[,2,1],method='spearman')
cor(res[,1,2],res[,2,2],method='spearman')
cor(res[,1,3],res[,2,3],method='spearman')

plot(res[,1,1],res[,2,1],type='p') #should look like a Gumbel
rect(0,0,1,1)
BiCopGofTest(res[,1,1],res[,2,1],family=4) #should indicate an acceptable fit
BiCopGofTest(res[,1,2],res[,2,2],family=4) #should indicate an acceptable fit
BiCopGofTest(res[,1,3],res[,2,3],family=4) #should indicate an acceptable fit

if (sum(sort(res[,1,1])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,1])==sort(m[,2]))==numpts &&
    sum(sort(res[,1,2])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,2])==sort(m[,2]))==numpts &&
    sum(sort(res[,1,3])==sort(m[,1]))==numpts &&
    sum(sort(res[,2,3])==sort(m[,2]))==numpts)
{
  print("passed")
} else
{
  print("Columns of output of copsurrog should be permutations of the corresponding columns of the input")
}
```

Test to see whether changing the copula
markedly influences the distribution
of the spatial mean:
```{r test_copsurrog2d_spatmean, echo=T, cache=T, cache.extra=list(mtime("copsurrog2d.R"),mtime("SkewnessAnd3CentMom.R"))}
set.seed(101)

#make the data
datcop<-rotCopula(claytonCopula(5,2))
d<-rCopula(10000,datcop)
d<-qnorm(d,mean=0,sd=1)

#change the copula
tarcop<-claytonCopula(3,2)
sur<-copsurrog2d(d,tarcop,"kendall",1000)

#see how the skewness of the spatial average
#is affected
source("SkewnessAnd3CentMom.R")
skdat<-myskns(apply(FUN=mean,X=d,MARGIN=1)) #skewness of spatial mean of data
mnres<-apply(FUN=mean,X=sur,MARGIN=c(1,3)) 
sksur<-apply(FUN=myskns,X=mnres,MARGIN=2) #skewnesses of spatial means of surrogate datasets
sum(sksur<skdat)/length(sksur) #skewnesses of surrogs should be less than that of data
range(sksur) #these should mostly be negative
skdat #this should be positive

#now do the same thing but preserve the spearman instead
sur<-copsurrog2d(d,tarcop,"spearman",1000)
skdat<-myskns(apply(FUN=mean,X=d,MARGIN=1))
mnres<-apply(FUN=mean,X=sur,MARGIN=c(1,3))
sksur<-apply(FUN=myskns,X=mnres,MARGIN=2)
sum(sksur<skdat)/length(sksur) #skewnesses of surrogs should be less than that of data
range(sksur) #these should mostly be negative
```

<!--Shya to add headers for other things that need to be tested, and let's discuss before you add the tests themselves-->